<a href="https://colab.research.google.com/github/moneypitak/multivariate/blob/main/Function_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Function**

```python
def function name(input) :

  do_something with  Input to produce Output

  return Output
  ```

### function มีส่วนสำคัญทั้งหมด 4 ส่วน

1 บอก python ว่าเราเขียนฟังก์ชั่น ชื่อะไร def function_name():(ขาดไม่ได้)

2.กำหนดตัวแปรที่จะเป็น input output (ขาดได้)

3.ส่วนประมวลผล do_something with input to get output (ขาดไม่ได้)

4.ส่วน output return output(ขาดได้)

In [ ]:
def print_name(name,surname,ID) : 
  st = f'ชื่อ {name}นามสกุล {surname} ID{ID}'
  return st
  print('outside function')

In [ ]:
print_name('มันนี่ ','พิทักษ์',' 623020532-3')

'ชื่อ มันนี่ นามสกุล พิทักษ์ ID 623020532-3'

In [ ]:
output_string = print_name('มันนี่ ','พิทักษ์',' 623020532-3')
print(output_string)

ชื่อ มันนี่ นามสกุล พิทักษ์ ID 623020532-3


ฟังก์ชั่นไม่จำเป็นต้องมี output

In [ ]:
def print_name2(surname,name,ID) : 
  st = f'ชื่อ {name}นามสกุล {surname} ID{ID}'
  return st
  print(st)

In [ ]:
print_name2('มันนี่ ','พิทักษ์',' 623020532-3')

'ชื่อ พิทักษ์นามสกุล มันนี่  ID 623020532-3'

In [ ]:
op2 = print_name2('มันนี่ ','พิทักษ์',' 623020532-3')

In [ ]:
print(op2)

ชื่อ พิทักษ์นามสกุล มันนี่  ID 623020532-3


ฟังก์ชั่นไม่จำเป็นต้องมี input


In [ ]:
def pi():
  return 3.14159265359

In [ ]:
#คำนวนพื้นที่วงกลมที่มีขนาดศูนย์กลางเท่ากับ 3
pi()*(1.5**2)

7.0685834705775

In [ ]:
def print_my_name():
  print('มันนี่ พิทักษ์ 623020532-3')

In [ ]:
print_my_name()

มันนี่ พิทักษ์ 623020532-3


input ของ function ใน python มีสองแบบ input ที่จำเป็นต้องใส่ กับ input ที่ไม่จำเป็นต้องใส่ (มีค่า default)

เราต้องเรียง input ที่จำเป็นต้องใส่ขึ้นก่อน

In [ ]:
def print_2lines_default(name, surname, ID, grade='F'):
  st = f'ชื่อ {name} นามสกุล {surname} รหัส {ID}'
  print(st)
  st2=f'เกรดวิชา Mutivariate >>> {grade}'
  print(st2)

In [ ]:
print_2lines_default('มันนี่ ',' พิทักษ์ ','623020532-3')

ชื่อ มันนี่  นามสกุล  พิทักษ์  รหัส 623020532-3
เกรดวิชา Mutivariate >>> F


In [ ]:
print_2lines_default('มันนี่ ',' พิทักษ์ ','623020532-3','A')

ชื่อ มันนี่  นามสกุล  พิทักษ์  รหัส 623020532-3
เกรดวิชา Mutivariate >>> A


เราสามารถเรียกฟังก์ชั่นโดยใช้ชื่อตัวแปรของฟังก์ชั่นช่วยได้

In [ ]:
print_name2(name='มันนี่ ',surname='พิทักษ์',ID='623020532-3')

'ชื่อ มันนี่ นามสกุล พิทักษ์ ID623020532-3'

HW ให้เขียน function คำนวณจำนวนวินาทีจาก เวลาต่อไปนี้

'14-15-31'

'13-00-01'

'05-49-44'

'00-00-16'

และ print ให้สวยงาม

In [ ]:
def time(money):
  h =  int (money.split('-')[0])*3600
  m = int (money.split('-')[1])*60
  s = int (money.split('-')[2])
  total = h+m+s
  print('แปลงเวลาทั้งหมดได้ =' ,total, 'วินาที')


In [ ]:
time('14-15-31') 

แปลงเวลาทั้งหมดได้ = 51331 วินาที


In [ ]:
time('13-00-01') 

แปลงเวลาทั้งหมดได้ = 46801 วินาที


In [ ]:
time('05-49-44') 

แปลงเวลาทั้งหมดได้ = 20984 วินาที


In [ ]:
time('00-00-16') 

แปลงเวลาทั้งหมดได้ = 16 วินาที


Numpy -> package สำหรับจัดการกับ Array ที่เป็นตัวเลข (Matrix)

์Num + py -> Numpy-Numerical + python

การใช้ package
1. ```import =ชื่อpackage``` #เรียกใช้ package 
2. ```ชื่อ package```.```ชื่อฟังก์ชัน``` เรียกใช้ function 

In [1]:
import numpy

data structure -> array

สร้าง array (numpy array)

In [3]:
mat_ex1 = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(mat_ex1)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


ชี้ค่าใน numpy array

In [5]:
mat_ex1[1,1] #[แถว,หลัก]

0.1

ถ้าไม่มี numpy array 


In [30]:
list_ex1 = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
print(list_ex1)

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]


In [19]:
list_ex1[1][1]

0.1

In [22]:
print(list_ex1) 
a = (list_ex1[1])
print(a)
print(a[1])

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]
[9.1, 0.1, 0.3]
0.1


Matrix Operations

data 2 แบบ -> matrix (2D array) , scalar (ตัวเลขค่าคงที่)

In [26]:
mat_ex1 = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(mat_ex1)
mat_ex2 = numpy.array([[2,3.7,5.9],[91,1.5,7.3]])
print(mat_ex2)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]


## บวกกับลบ matrix เอาตัวเลขตำแหน่งเดียวกันมาบวกกันหรือลบกัน
(หน้าตาของ matrixค้องเหมือนกัน)

In [37]:
mat_ex3 = mat_ex1 + mat_ex2 
print(mat_ex3)
mat_ex4 = mat_ex1 + mat_ex2
print(mat_ex4) 

[[  7.2   6.7  10.4]
 [100.1   1.6   7.6]]
[[  7.2   6.7  10.4]
 [100.1   1.6   7.6]]


การตรวจสอบขนาดของ matrix

In [33]:
mat_ex3.shape[0] #คู่อันดับ

2

## คูณ matrix

In [ ]:
print(mat_ex1)
print(mat_ex2)

In [41]:
mat_ex1 * mat_ex2

array([[1.040e+01, 1.110e+01, 2.655e+01],
       [8.281e+02, 1.500e-01, 2.190e+00]])

## การคูณ matrix (แถวคูณหลัก)
(หลักของ matrix ตัวข้างหน้า ต้องเท่ากับแถวของ matrix ตัวข้างหลัง)

dot product ((AAA,x),(x,ZZZ)) = (AAA,ZZZ)

In [46]:
## numpy.dot(mat_ex1,mat_ex2) ต้องใส่ .T

In [44]:
print(mat_ex1)
print(mat_ex1.shape)
print(mat_ex2)
print(mat_ex2.shape)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
(2, 3)
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]
(2, 3)


# Transpose กลับแถวเป็นหลักกลับหลักเป็นแถว

```matrix.T```

In [47]:
print(mat_ex2)
print(mat_ex2.shape)

[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]
(2, 3)


In [48]:
print(mat_ex2.T)
print(mat_ex2.T.shape)

[[ 2.  91. ]
 [ 3.7  1.5]
 [ 5.9  7.3]]
(3, 2)


In [45]:
numpy.dot(mat_ex1,mat_ex2.T) #(2,3).(3,2)

array([[ 48.05, 510.55],
       [ 20.34, 830.44]])

In [50]:
numpy.dot(mat_ex1.T,mat_ex2) #(2,3).(3,2)

array([[838.5 ,  32.89,  97.11],
       [ 15.1 ,  11.25,  18.43],
       [ 36.3 ,  17.1 ,  28.74]])

HW4 อธิบายการหา Determinant และ Inverse matrix(รูปและคำอธิบาย)

~~Pandas~~
